### ISSUE TITLE
Cluster Stacks for Hetzner

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/cluster-stacks#108]
/kind feature

**Describe the solution you'd like**
Title says all

**Comment by paulphys** [comment]
+1 for the idea.
There's also already the [Cluster API Provider Hetzner](https://github.com/syself/cluster-api-provider-hetzner) maintained by syself. Might be worth looking into.

**Comment by chess-knight** [comment]
> +1 for the idea. There's also already the [Cluster API Provider Hetzner](https://github.com/syself/cluster-api-provider-hetzner) maintained by syself. Might be worth looking into.

Yes, CAPH is exactly what I want to use. It can handle cloud instances and also bare metal ones.
