### ISSUE TITLE
Wrong K8s version referenced in helm values

### ISSUE THREAD

**Issue by ghost** [SovereignCloudStack/cluster-stacks#135]
/kind bug

There was a hit and a miss and the [values file](https://github.com/SovereignCloudStack/cluster-stacks/blob/def1048d03d615d8fbf555d9d827bfb65b446e14/providers/openstack/scs/cluster-class/values.yaml#L17) of cluster-class still references the 1.27 version images.

**Comment by DEiselt** [comment]
This is also not updated by the `generate_version` script. Working on a fix
