### ISSUE TITLE
Cluster Stacks for Metal³

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/cluster-stacks#21]
As an SCS operator, I want to be able to manage bare metal hosts using Kubernetes, so I can deploy Kubernetes on it using the Cluster Stacks approach

- [x] Create Cluster Class for Metal³
- [ ] #98

**Comment by chess-knight** [comment]
Upstream ClusterClass support is in progress. There is already approved PR https://github.com/metal3-io/cluster-api-provider-metal3/pull/1405.
