### ISSUE TITLE
Update CAPO related resources to v1beta1

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/cluster-stacks#68]
/kind feature

**Describe the solution you'd like**
[CAPO 0.10.0](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.10.0) is out and updates the APIs to v1beta1. As recommended in the release notes we should switch to this asap. Especially since it solves problems we marked as known issues in our R6 release notes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by paulphys** [comment]
[Breaking changes](https://cluster-api-openstack.sigs.k8s.io/topics/crd-changes/v1alpha7-to-v1beta1#change-to-nodecidr-and-dnsnameservers)
