### ISSUE TITLE
Upgrades do not work with apiserver_loadbalancer set to none

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/cluster-stacks#88]
When using 1 control-plane node and apiserver_loadbalancer type none, capo gets stuck upgrading a cluster.

**Comment by chess-knight** [comment]
According to the CAPO - `only cluster with LBaaS can be upgraded` https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/README.md#features.

**Comment by mxmxchere** [comment]
Thanks @chess-knight. you almost always have the spot-on relevant link :)
