### ISSUE TITLE
cluster-stack `scs` catch up with `alpha`

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/cluster-stacks#93]
- [x] v1beta
- [x] oidc
- [ ] for now, no extra folders per k8s version, either keep 1-27 or rename to `all_versions` or remove folder-hierarchy for the version
- [ ] last step: remove alpha and wooctavia folders

**Comment by DEiselt** [comment]
Hierarchy updates will be moved to another issue
